import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import PageContainer from '@/components/page-components/page-container';
import PageHeader from '@/components/page-components/page-header';
import AuthProvider from '@/modules/auth/auth-provider';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<AuthProvider>
			<html lang="en">
				<body className={`${geistSans.variable} ${geistMono.variable}`}>
					<PageHeader />
					<PageContainer>{children}</PageContainer>
				</body>
			</html>
		</AuthProvider>
	);
}
